### ISSUE TITLE
sesuaikan data dokumen program bantuan dan dokument / kelengkapan penduduk

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#115]
Perlu disesuaikan kembali bagian dokumen di rincian data penduduk

<img width="754" alt="image" src="https://user-images.githubusercontent.com/59082428/231630691-21f51a8b-493b-4278-9752-0c2fbbc2feea.png">

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenKab/pull/123
