### ISSUE TITLE
Sesuaikan dasbor dengan adanya statistik 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#117]
![image](https://user-images.githubusercontent.com/59082428/232200262-7b05e683-546a-4635-b87d-7fbf4b2cd3e0.png)
--------------------
Seperti contoh dibawah ini : 
<img width="644" alt="image" src="https://user-images.githubusercontent.com/59082428/232201926-7f1c45f8-7039-4c4a-8be0-29f66589bc49.png">

1. Jumlah Penduduk 
    - Laki - laki & Perempuan
 2. Jumlah Keluarga 
 3. Jumlah Bantuan
 4. Jumlah RTM

Statistik Menampilkan Data Penduduk : setiap bulannya jumlah akan terlihat meningkat atau berkurang selama setahun.
1. Laki - laki 
2. Perempuan

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenKab/pull/124
