### ISSUE TITLE
Tambahakan Filter Pada Data Penduduk 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#118]
<img width="953" alt="image" src="https://user-images.githubusercontent.com/59082428/232203137-3756dbdb-371d-43ba-9539-969a9501472a.png">

1. Kecamatan
2. Kelurahan
3. Status Penduduk
4. Status Dasar
5. Jenis Kelamin 

Sesuai Data seperti OpenSID
<img width="751" alt="image" src="https://user-images.githubusercontent.com/59082428/232203349-31da3eea-fe03-41a3-8069-ddc83cff5569.png">

*keterangan :
-------------------------
Mohon di perhatikan pemilihan wilayah itu adalah daftar kecamatan dimana ketika dipilih maka masih perlu memilih kelurahan 
untuk dapat menampilkan data penduduk kelurahan tersebut.

**Comment by agungsugiarto** [comment]
mas @vickyrolanda, mohon dipisah issuenya untuk filter dan cetak

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenKab/pull/125
