### ISSUE TITLE
Tambahakan Filter & Cetak Pada Data Bantuan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#119]
<img width="754" alt="image" src="https://user-images.githubusercontent.com/59082428/232205505-a9d4513e-07b1-47e3-ac7f-1b14a64973ea.png">

-----------
Tambahan Filter 
0. PIlih Kelurahan setelah pilih kecamatan
1. Jenis Sararan 
2. Pilih Tahun 

<img width="945" alt="image" src="https://user-images.githubusercontent.com/59082428/232205880-b9c7d2b8-3a3c-4470-86c9-48bbcd0e1174.png">

***keterangan :**
Mohon di perhatikan pemilihan wilayah itu adalah daftar kecamatan dimana ketika dipilih maka masih perlu memilih kelurahan
untuk dapat menampilkan data penduduk kelurahan tersebut.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenKab/pull/129
