### ISSUE TITLE
Tambahan Filter Pada data Statistik Penduduk

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#120]
Pada data statistik masih belum ada filter berdasarkan 
0. Kecamatan
1. Kelurahan
2. Bulan
3. Tahun

<img width="775" alt="image" src="https://user-images.githubusercontent.com/59082428/232206288-b0f34abf-88af-48bd-850e-37ff65ba08d1.png">

Perlu di tambahkan proses : 
1. Pilih Wilayah (data kecamatan)
2. Lalu akan muncul data kelurahan 
3. tambahkan filter bulan (pada data statistik)
4. tahun   (pada data statistik)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenKab/pull/133
