### ISSUE TITLE
Tambahakan Cetak Pada Data Penduduk 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#126]
<img width="953" alt="image" src="https://user-images.githubusercontent.com/59082428/232203137-3756dbdb-371d-43ba-9539-969a9501472a.png">

Gambar di atas menunjukan belum ada fungsi cetak, mohon untuk menambahkan fungsi cetak sesuai seperti OpenSID
<img width="751" alt="image" src="https://user-images.githubusercontent.com/59082428/232203349-31da3eea-fe03-41a3-8069-ddc83cff5569.png">

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenKab/pull/134
