### ISSUE TITLE
Pisahkan API dari OpenKab sehingga API dapat jalan terpisah dari OpenKab & OpenSID database gabungan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#128]
Pemisahan API disini adalah API tetap dibuat pada repo OpenKab, namun pemanggilan data dari database gabungan tidak dilakukan langsung query ke database gabungan, melainkan melalui API yang di rancang dan dipanggil pada view OpenKab. 

Seharusnya pada pengembangan sudah diterapkan seperti konsep diatas mungkin perlu di cekkembali, jika masih ada yang diterapkan query langsung maka perlu dibuat API dan diterapkan pada query. 

batasan pengerjaan isi disini adalah  : 
1. Pastikan pengambilan data dari database gabungan melalui API
2. Jika masih ada maka perlu dibuat API (jika terlalu banyak maka kita akan pecah issue ini)
3. Untuk DB bawaan OpenKab tidak masalah langsung query seperti biasanya 

Lalu, 
- [x] #324

**Comment by pandigresik** [comment]
Apakah ini dibuat menjadi 2 aplikasi ataukah tetap satu aplikasi namun dengan kondisi berikut ini :

1. Openkab
2. Api gabungan
3. Openkab dan Api gabungan
