### ISSUE TITLE
error mysql  isn't in GROUP BY 

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenKab#130]
![image](https://user-images.githubusercontent.com/20056421/233175978-efb6fcd3-6f00-43ea-b454-64b975031923.png)

**Comment by apidong** [comment]
@vickyrolanda @andifahruddinakas apakah perlu di perbaiki malalui coding pak?

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenKab/pull/170
