### ISSUE TITLE
Tambahan Filter Pada data Statistik RTM

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#136]
Pada data statistik masih belum ada filter berdasarkan 
0. Kecamatan
1. Kelurahan
2. Bulan
3. Tahun

Perlu di tambahkan proses : 
1. Pilih Wilayah (data kecamatan)
2. Lalu akan muncul data kelurahan 
3. tambahkan filter bulan (pada data statistik)
4. tahun   (pada data statistik)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenKab/pull/145
