### ISSUE TITLE
Filter Global kecamatan dan Desa tidak berfungsi

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenKab#166]
dengan filter data tetap 
![image](https://github.com/OpenSID/OpenKab/assets/20056421/9f61843e-d2ce-4a3f-aff5-6a65586dc167)

**Comment by andifahruddinakas** [comment]
Solusi : 
- [ ] Jangan gunakan session
- [ ] Kirim parameter config (kode_kecamtan, kode_desa) ke filter API

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenKab/pull/173
