### ISSUE TITLE
Sediakan Fitur Mutasi penduduk antar kelurahan melalui API

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#17]
Melalui API yang di buat untuk melakukan mutasi, perlu dibuat agar tampilannya mudah di pahami prosesnya : 
1. Pilih warga yang ingin di mutasi
2. Ubah Status  Dasar
3. Pilih Mutasi 
4. lalu pilih wilayah / kelurahan yang akan di tuju. 

maka atas dasar proses di atas data yang semulanya ada di kelurahan A akan pindah ke kelurahan B dan database gabungan akan menyesuaikan sesuai data yang di proses melalui API ini.

**Comment by andifahruddinakas** [comment]
mas @vickyrolanda, untuk issue ini perlu dibahas mengenai gambar/file penduduk apakah perlu dipindahkan atau hanya data sja?
