### ISSUE TITLE
Error redirect setelah login

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenKab#171]
setelah login succes login. halaman bukan mengarah ke home, tetapi ke halaman https://simatik.bimakota.go.id/pengaturan/logo
![image](https://github.com/OpenSID/OpenKab/assets/20056421/812b2f8f-8a1d-4dda-9ef2-d0f5d60feb80)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenKab/pull/172
