### ISSUE TITLE
Performa statistik perlu disesuaikan untuk data cukup besar

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#179]
1. Setiap pindah menu statistik untuk simatik akan terasa cukup lambat walaupun kadang kebuka namun jika prosesnya cukup besar akan terjadi server timeout 505 seperti dibawah ini : 

<img width="763" alt="image" src="https://github.com/OpenSID/OpenKab/assets/59082428/c7350a05-cbe5-487a-a072-f2157543fca1">

yang di harapkan : 
1. Merubah konsep query pada statistik agar proses tiap pindah menu akan terasa alus.
2. Tidak error timeout 505

Solusi Teknis Referensi : https://demyanov.dev/using-php-apache-kafka 
https://github.com/quipo/kafka-php

Apache Kafka adalah sebuah platform streaming data open-source yang digunakan untuk mengirim dan menerima data secara real-time dalam skala besar. Kafka dirancang untuk mengatasi tantangan pemrosesan data yang kompleks dan memungkinkan aplikasi dan sistem untuk berkomunikasi secara efisien dengan adanya aliran data yang kontinu.

https://gustho.medium.com/integrasi-data-dengan-kafka-3c66ddbcb25c

**Comment by apidong** [comment]
> 1. Setiap pindah menu statistik untuk simatik akan terasa cukup lambat walaupun kadang kebuka namun jika prosesnya cukup besar akan terjadi server timeout 505 seperti dibawah ini :
> 
> <img alt="image" width="763" src="https://user-images.githubusercontent.com/59082428/239854161-c7350a05-cbe5-487a-a072-f2157543fca1.png">
> yang di harapkan :
> 
> 1. Merubah konsep query pada statistik agar proses tiap pindah menu akan terasa alus.
> 2. Tidak error timeout 505
> 
> Solusi Teknis Referensi : https://demyanov.dev/using-php-apache-kafka https://github.com/quipo/kafka-php
> 
> Apache Kafka adalah sebuah platform streaming data open-source yang digunakan untuk mengirim dan menerima data secara real-time dalam skala besar. Kafka dirancang untuk mengatasi tantangan pemrosesan data yang kompleks dan memungkinkan aplikasi dan sistem untuk berkomunikasi secara efisien dengan adanya aliran data yang kontinu.
> 
> https://gustho.medium.com/integrasi-data-dengan-kafka-3c66ddbcb25c

apakah data nya dibuat model streaming pak?

**Comment by apidong** [comment]
sepertinya kurang cocok dengan apa yang kita inginkan pak
https://halovina.com/7-studi-kasus-penggunaan-apache-kafka/

**Comment by apidong** [comment]
![image](https://github.com/OpenSID/OpenKab/assets/20056421/c6df0d15-b0d0-4ef3-8256-98ee4805456b)

**Comment by apidong** [comment]
solusinya sudah ketemu. tambahkan index ke tabal log_penduduk.
