### ISSUE TITLE
Sediakan API Untuk  melakukan mutasi data penduduk antar kelurahan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#18]
API dengan method POST digunakan untuk merubah status kependudukan warga dari satu kelurahan ke pendudukan kelurahan lainnya, proses ini akan juga merubah data yang ada di database gabungan.

Sehingga ketika warga di mutasi maka status kependudukan akan berubah di database gabungan dan disesuaikan berdasarkan wilayah yang dipilih melalui OpenKab. 

Umumnya di OpenSID ada fitur merubah status dengan langkah : 
1. Kependudukan -> menu Penduduk
2. Pilih aksi salah satu warga 
3. Ubah Status Dasar
4. Pilih Pindah
5. Pilih Tujuan (Pindah Keluar desa/kelurahan 
6. Isi alamat Tujuan
7. Tanggal Pristiwa & Tanggal Lapor
8. lalu catatan peristiwa.

Nah langkah diatas umumnya di lakukan diOpenSID, maka perlu ada proses diatas dapat dilakukan di OpenKab
dimana sifat datanya bisa menyesuaikan sifat data yang tersimpan dari aksi seperti diatas. 
POST API dari OpenKab ke OpenSID database gabungan
1. ID Penduduk
2. Status Dasar (mengikuti standar OpenSID lihat status dasar khusus PINDAH 
3. Tujuan Pindah sudah terpilih atau menyimpan nilai default sesuai tujuan pindah diatas yaitu (Pindah Keluar desa/kelurahan)
4. Alamat Tujuan  (isi sesuai tujuan wilayah nama kelurahan dan alamat yg dapat diisi melalui OpenKab 
   misalkan defaultnya Kelurahan A alamat dinamis sesuaikan yang diisi di OpenSID
5. Tanggal Peristiwa & tanggal lapor di tentukan melalui OpenKab 
6. Lalu Catatan Peristiwa di tentukan melalui OpenKab 

lalu data itu akan di POST ke OpenSID database gabungan maka otomatis akan juga insert ke warga datang di keluarahan baru sesuai data warga. 

misalkan : 
Awal di kelurahan A : Proses update status dasar dari OpenKab 
tujuan di kelurahan B : Proses insert penduduk datang 

2 Proses diatas dilakukan bersamaan ketika proses mutasi di POST melalui OpenKab.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenKab/pull/163
