### ISSUE TITLE
Perbaikan minor terkait tampilan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#184]
1. Tambahkan spasi pada icon + Tambah 
<img width="244" alt="image" src="https://github.com/OpenSID/OpenKab/assets/59082428/1935fb03-9427-41df-b0db-3523611b7451">

2. Sembunyikan icon berikut ini dari header 
<img width="120" alt="image" src="https://github.com/OpenSID/OpenKab/assets/59082428/31a561c9-628f-461d-985b-9ef7c82954e4">

3. Ubah Nama OpenKAB sesuai dari pengaturan nama aplikasi 
<img width="183" alt="image" src="https://github.com/OpenSID/OpenKab/assets/59082428/7e5e5a6c-eb51-41b7-99c9-b0e45310bf38">

4. Sesuaikan tampilan icon / logo sesuai dengan tinggi yang mengikuti lebar jadi batasi lebarnya agar tampilan tidak ketarik seperti ini : 

tampilan di login : 

<img width="213" alt="image" src="https://github.com/OpenSID/OpenKab/assets/59082428/3f61412b-a614-4163-911c-2e686857ebd4">

di identitas desa : 

<img width="334" alt="image" src="https://github.com/OpenSID/OpenKab/assets/59082428/2fc7c9ed-18e0-484c-81b2-3fbbf7f6f1db">

**Comment by apidong** [comment]
untuk logo. memang saya resize. karena kalau tidak di resize. akan jadi seperti ini tampilannya 
![image](https://github.com/OpenSID/OpenKab/assets/20056421/f660b3ad-b8e2-4427-9e9d-1f9175af2885)

**Comment by apidong** [comment]
- [ ] Tambahkan spasi pada icon + Tambah
- [ ] Sembunyikan icon berikut ini dari header
- [ ] Ubah Nama OpenKAB sesuai dari pengaturan nama aplikasi
- [ ] Sesuaikan tampilan icon / logo sesuai dengan tinggi yang mengikuti lebar jadi batasi lebarnya agar tampilan tidak ketarik
