### ISSUE TITLE
Sediakan API untuk manajemen data Bantuan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#19]
Jenis Bantuan Yang di tentukan oleh OpenKab adalah jenis bantuan yang sudah FIX, 
dimana database gabungan tidak dapat merubah data melainkan hanya dapat membaca dan mengisi bantuan saja.

Batasan pengerjaan : 
1. Tambah Bantuan melalui OpenKab
2. Simpan data bantuan di Database OpenKab
3. Kirim data bantuan ke database gabungan sebanyak config_id yang ada di tabel config
4. Sehingga data bantuan akan terdistribusi sesuai config_id
5. lalu jika data tersedia, maka proses update dilakukan dengan merubah jenis bantuan berdasarkan id bantuan openkab.

**Comment by yogiperdana** [comment]
Mas @vickyrolanda mohon lengkapi issuenya mas terkait teknis penerapan dan alurnya mau bagaimana

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenKab/pull/139
