### ISSUE TITLE
Filter pada bantuan tidak berjalan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#206]
1. lihat filter pada bagian sasaran muncul seperti berikut ini : 
<img width="371" alt="image" src="https://github.com/OpenSID/OpenKab/assets/59082428/5deae030-202c-4e38-ad2f-cd4eed9114c2">

2. Lihat filter pada bagian tahun muncul seperti beriku ini : 
<img width="742" alt="image" src="https://github.com/OpenSID/OpenKab/assets/59082428/e669742b-ee84-430b-9f7f-2522816dab2e">

**Comment by FirlianiF** [comment]
mas @vickyrolanda saya tidak dapat mereplikasi issue ini,
pakai db_gabungan yang di local saya aman, data di form pencarian berjalan dengan baik, dan sudah dicoba pakai db_kotabima juga filter dapat berjalan.

**Comment by scqolbu24** [comment]
mas @vickyrolanda untuk uji cobanya di server mana mas? di server kota bima atau devopenkab?

**Comment by scqolbu24** [comment]
Hasil testing di server devopenkab:
![image](https://github.com/OpenSID/OpenKab/assets/68048807/c0224e36-c995-4622-ac94-71d375e0ceb3)

**Comment by scqolbu24** [comment]
Sudah diperbaiki mas, berikut hasil testingnya:
![image](https://github.com/OpenSID/OpenKab/assets/68048807/e211fc58-d356-4640-a0bb-8f3595d5849b)
