### ISSUE TITLE
Ubah Semua Penamaan OpenKAB menjadi OpenKab

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenKab#226]
![openkab login](https://github.com/OpenSID/OpenKab/assets/68048807/92b8bb4a-56e4-41f3-a75a-9dfe4a01b1cf)
![sidebar](https://github.com/OpenSID/OpenKab/assets/68048807/04c2ba49-a37c-4493-acc4-55b0e4f47350)

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/OpenKab/pull/227
