### ISSUE TITLE
Lengkapi data pada pengaturan identitas daerah

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#233]
http://127.0.0.1:8000/pengaturan/identitas
Sesuaikan pilihan Kabupaten untuk bertahap,
1. Pilih terlebih dahulu provinsi.
2. lalu pilih kabupaten. 
Data ini bisa diambil melalui API ke pantau. 

untuk mengampil data API hanya di panggil pada halaman pengaturan tersebut tidak untuk global, mengatisipasi jika terjadi masalah pada pantau tidak menjadi kendala pada penggunaan OpenKab.

![image](https://github.com/OpenSID/OpenKab/assets/59082428/af573960-2bf5-4a09-a1f9-1029136f1eb0)

**Comment by pandigresik** [comment]
Data apa saja yang perlu dilengkapi ?
