### ISSUE TITLE
Cek halaman pengaturan aplikasi di devopenkab

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#240]
Silahkan di cek kenpa di devopenkab halaman pengaturan aplikasi tidak tampil. 
![image](https://github.com/OpenSID/OpenKab/assets/59082428/36dc3a6b-8abe-4148-bb2d-9bb99d677617)

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenKab/assets/1853475/c6b24adf-ea8a-444f-a236-c3542bcec8c5)

Di local juga sama

**Comment by pandigresik** [comment]
Setelah dilakukan pengecekan dikarenakan data pengaturan dengan kategori openkab tidak ditemukan di database. 
Solusi sementara tambahkan data melalui query, dan di code sudah ditentukan harus ambil data dengan config_id bernilai id baris pertama tabel config
INSERT INTO setting_aplikasi (config_id,judul,`key`,value,keterangan,jenis,`option`,`attribute`,kategori) VALUES
	 (1,'Warna Tema','warna_tema',NULL,'Warna tema untuk halaman website','color',NULL,NULL,'openkab');
	
INSERT INTO setting_aplikasi (config_id,judul,`key`,value,keterangan,jenis,`option`,`attribute`,kategori) VALUES
	 (1,'Lock Theme','lock_theme',NULL,'Setting kunci tema website','option','{"1":"Aktif","0":"Tidak Aktif"}',NULL,'openkab');

![image](https://github.com/OpenSID/OpenKab/assets/1853475/d7991907-f271-4a2f-9189-de1ff65363ab)
