### ISSUE TITLE
Tambahkan fungsi pengaturan bagan pemerintah daerah

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#255]
Halaman ini akan tampil pada struktur bagan, tambahkan tampilan struktur bagan seperti yang ada di OpenSID.
https://berputar.opendesa.id/pengurus/bagan/bpd
![image](https://github.com/OpenSID/OpenKab/assets/59082428/5538ff2d-c8b3-445e-9358-7cc4f67fa518)

**Comment by pandigresik** [comment]
Ini seharusnya mengikuti data struktur organisasi pada table department dan pejabat daerah ya ?

**Comment by pandigresik** [comment]
https://berputar.opendesa.id/pengurus/bagan/bpd pakai highcharts, sepertinya ada lisensinya jika sudah masuk ke production
https://shop.highcharts.com/
