### ISSUE TITLE
OpenKab perlu dibuat database seeder untuk demo data OpenSID

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#268]
Data demo yang dibutuhkan : 
Nantinya Data akan kita gunakan untuk devpremium.opendesa.id maka devopenkab.opendesa.id akan menggunakan database yang di pakai pada devpremium.opendesa.id maka dibutuhkan data demo untuk penerapan di devpremium.opendesa.id.

data demo dijalankan melalui OpenKab menggunakan seeder untuk kebutuhan demo di devopenkab.opendesa.id data yang dibutuhkan semua data yang tampil pada OpenKab.

Tema pada penggunaan devpremium.opendesa.id juga bisa menggunakan tema kustom untuk kota bima karena ada fungsi yang penerapannya masih pada tema tersebut.

1. Data Penduduk  
2. Data Bantuan 
3. Kategori Bantuan
4. Kategori Berita
5. Log Penduduk kebutuhan data statistik

Tujuan penerapan ini agar devopenkab.opendesa.id & devpremium.opendesa.id bisa menjadi demo dan jika ada pertemuan bisa digunakan untuk menjalankan fungsi dari OpenKab.

**Comment by pandigresik** [comment]
Sepertinya bisa pakai package orangehill/iseed, namun untuk data opensid_gabungan sepertinya sangat besar sekali datanya

**Comment by eddieridwan** [comment]
Perlu bedakan kebutuhan data, termasuk:

1. data untuk pengujian fungsional. Tidak harus besar, yang penting adalah mencakup setiap alur aplikasi
2. data untuk contoh demo bagi calon pengguna atau untuk pemaparan oleh pegiat. Tidak harus besar, yang penting adalah mencakup sasaran demo
3. data untuk pengujian performa. Harus sesuai dengan dengan perkiraan jumlah data terbesar. Jadi bisa sangat besar.

Yaitu, untuk issue ini harus lebih rinci kegunaan data yg akan dihasilkan.
