### ISSUE TITLE
Menu Halaman

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#285]
Menu ini tujuan untuk membuat halaman yang sifatnya statis perhalaman.
Komponennya kita bisa berikan yang standar seperti,

Referensi yang bisa kita gunakan seperti yang ada di OpenSID
![image](https://github.com/OpenSID/OpenKab/assets/59082428/e2c7bdef-89e3-4a3c-a707-3cb858c1a329)

1. Judul halaman
   - Judul artikel minimal 5 karakter dan maksimal 200 karakter
2. Isi Halaman
   - Bisa menggunakan TinyMCE
3. Gambar
   - gambar ini bisa kita gunakan sebagai thumbnil atau banner pada halaman depan.

Struktur data :
1. id_halaman 
2. judul
3. slug
4. isi_halaman
5. tgl_posting
6. status "Aktif","Non-aktif"

**Comment by pandigresik** [comment]
[Screencast from 14-09-23 10:40:11.webm](https://github.com/OpenSID/OpenKab/assets/1853475/cb072fdd-6779-4822-a7b1-6158b2a41962)
