### ISSUE TITLE
Halaman Kategori Artikel

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#286]
Kategori digunakan untuk mengklasifikasi artikel agar mengikuti standar artikel, dan beguna juga untuk menjadi informasi yang dapat di klasifikasikan perkelompok kategori.

Referensi bisa tampilan bisa seperti berikut ini : 
![image](https://github.com/OpenSID/OpenKab/assets/59082428/4bf5b33b-470e-4af4-a15e-384f383229e0)

Form inputan bisa seperti sebagai berikut : 
1. Nama Kategori 
2. Status "Ya"."Tidak"

Struktur Data bisa mengikuti sebagai berikut ini  : 
1. id_kategori
2. nama_kategori
3. slug
4. status
5. tanggal_buat

**Comment by pandigresik** [comment]
Struktur table kita gunakan seperti dibawah ini, kita pakai id bukan id_kategori mengikuti konvensi dari laravel

![image](https://github.com/OpenSID/OpenKab/assets/1853475/df0f85f0-0514-401c-8f7a-b893347701bf)
