### ISSUE TITLE
Buat struktur database Openkab

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#3]
1. OpenKab dapat menampilkan data yang di ambil melalui API OpenKab
   - OpenKab akan di config melalui .env untuk remote sql ke database gabungan
2 OpenKab memiliki database tersendiri untuk mengatur 
   - Identitas OpenKab
   - Manajemen pengguna OpenKab
   - Rul Pengguna 
   - Modul menu - menu 
   - Lupa Password

**Comment by yogiperdana** [comment]
Belum ada ada keterangan tabel yang unik mas @vickyrolanda

**Comment by yogiperdana** [comment]
Lalu di tabel user kolom username apakah benar username dan email null mas?
