### ISSUE TITLE
Tambahkan data desa/kelurahan sesuai parameter desa teraktif

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#323]
![image](https://github.com/OpenSID/OpenKab/assets/59082428/bbc0225b-be29-4227-a74f-6e2e785f6648)

Sesuaikan tampilan desa teraktif berdasarkan beberapa parameter berikut ini : 
1. Penduduk != Kosong
2. RTM != Kosong
3. Jumlah Artikel Terbanyak 
4. Jumlah visitor terbanyak (mungkin bisa ambil dari sini sys_traffic berdasarkan config_id) 

untuk saat ini 4 parameter diatas bisa dijadikan parameter. 

lalu untuk gambar thumbnail bisa ambil dari penerapan gambar dibawah ini mas (mungkin dari table setting_aplikasi dengan parameter config_id & key = latar_website   : 
![image](https://github.com/OpenSID/OpenKab/assets/59082428/a54ef91c-ab53-4241-bf26-20c5633a2152)

**Comment by pandigresik** [comment]
lalu untuk gambar thumbnail bisa ambil dari penerapan gambar dibawah ini mas (mungkin dari table setting_aplikasi dengan parameter config_id & key = latar_website :

untuk gambar sepertinya tidak bisa ambil dari variabel tersebut, karena lokasi file asli tidak diketahui. Akses openkab hanya ke database gabungan bukan ke url masing2 SID desa
