### ISSUE TITLE
Error saat nambah slide & edit slide devopenkab

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#328]
mas @pandigresik ,mohon bantuannya untuk di cek pada server devopenkab, ketika nambah slide & edit terjadi error seprti gambar dibawah ini : 
![image](https://github.com/OpenSID/OpenKab/assets/59082428/c53e5de1-91f4-4ce0-aff0-d958d3489edb)

Nambah Artikel juga error mas @pandigresik 

Gambar yang ingin di upload : 
![banner-1](https://github.com/OpenSID/OpenKab/assets/59082428/56b558d0-5197-457f-818c-8eb7bf63441b)
![banner-2](https://github.com/OpenSID/OpenKab/assets/59082428/a86c05ce-161b-424c-9ac3-6fec0dd0689e)

**Comment by pandigresik** [comment]
Sudah diperbaiki, hal ini dikarenakan folder uploads belum ada di /var/www/html/openkab/storage/app/public/uploads

![image](https://github.com/OpenSID/OpenKab/assets/1853475/de817f76-13b3-4969-9e24-d85cb14c9ab3)
