### ISSUE TITLE
Sediakan API Untuk data rincian berdsarkan No KK

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#34]
Issue ini untuk menampilkan data rincian per KK berdasarkan parameter No KK yang ada di daftar penduduk 

1. Lihat bagian No KK
<img width="716" alt="image" src="https://user-images.githubusercontent.com/59082428/230793717-5d621b88-bf73-430a-9be4-e8b8cab58309.png">

2. Ketika no kka diklik masuk ke rincian data kka seperti berikut ini : 
<img width="768" alt="image" src="https://user-images.githubusercontent.com/59082428/230793766-66b1ded8-70b7-4555-bf9a-3cb0bc2303cf.png">

dari kebutuhan diatas maka diperlukan API untuk menampilkan data rincian kka seperti poin no 2.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenKab/pull/108
