### ISSUE TITLE
Dasbor awal

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#346]
![Demografi - 1](https://github.com/OpenSID/OpenKab/assets/59082428/d522bc0a-c0b9-4794-9726-057dbbbdfce2)
pada bagian data di dasbor ini terdapat beberapa data yang perlu disesuaikan : 

Data sudah ada di API tersedia saat ini 
1.	Kecamatan
2.	Kelurahan / desa 
3.	Jumlah Penduduk
4.	Jumlah KK 

data diatas sudah dapat diambil dari API yang tersedia karena sudah digunakan juga didalam.

Data sumber dari prodeskel : 
1.	Total Luas Wilayah ( https://github.com/OpenSID/modul-prodeskel/pull/49/ ) 
        - Luas Desa (Ha)
2.	Total Lahan Pertanian ( https://github.com/OpenSID/modul-prodeskel/issues/10)
        -  Total dari (Total Lahan Kehutanan + Total Lahan Perternakan + Total Perkebunan ) 
3.	Total Perkebunan (https://github.com/OpenSID/modul-prodeskel/pull/57)
       - Luas Perkebunan Rakyat (Ha)
       - Luas Perkebunan Swasta/Negara (Ha)
4.	Total Lahan Kehutanan	 (https://github.com/OpenSID/modul-prodeskel/pull/66)
       - Luas Hutan (Ha)
5.	Total Lahan Perternakan (https://github.com/OpenSID/modul-prodeskel/pull/68) 
       - Luas Lahan Gembalaan (Ha)

Tampilan MAP, apakah bisa diambil berdasarkan lokasi kabupaten sehingga yang tampil map kabupten tersebut.

**Comment by pandigresik** [comment]
untuk 
Total Perkebunan (https://github.com/OpenSID/modul-prodeskel/pull/57)
Luas Perkebunan Rakyat (Ha)
Luas Perkebunan Swasta/Negara (Ha)

saya cek tidak ada data luas perkebunan pada fitur tersebut
