### ISSUE TITLE
Manajemen jenis data bantuan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#35]
untuk tampilkan Data Bantuan di OpenKab, perlu dipikirkan cara menampilkan jenis program yg berbeda-beda di antara kelurahan. 

Mungkin gabungkan jenis program menurut namanya. Mungkin harus persis sama.

Penyeragaman jenis program hanya dapat dilakukan setelah OpenKab Tahap Kedua. 

Nantipun setelah ada penentuan jenis program dari OpenKab, tetap perlu ada cara untuk tahu mana yg ditentukan OpenKab dan yg lokal dari kelurahan.

Jadi yg dapat ditampilkan di Tahap Pertama terbatas pada jenis program yg ditentukan lokal dari kelurahan.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenKab/pull/141
