### ISSUE TITLE
Tambahkan Pengaturan API pada OpenKab

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#376]
Pengaturan ini digunakan untuk menghubungkan OpenKab dengan API OpenKab yang telah dipisahkan . 

Pengaturanyang diperlukan : 

1.  Host (domain utama) tujuannya agar otorisasi harus berada apda host yang sama
2.  URL API 

untuk auth bisa di sesuaikan bahwa menggunakan username & password OpenKab.

**Comment by agungsugiarto** [comment]
mas @vickyrolanda karena api openkab tidak disediakan ui, jadi pengatuan langsung pada .env yaitu `OPENKAB_BASE_URL`, kemudian untuk autentikasi seperti yang dibahas pada pertemuan menggunakan dari aplikasi openkab yaitu sanctum token.
