### ISSUE TITLE
Tambahkan pengaturan menu statistik pada OpenKab

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#380]
![Image](https://github.com/user-attachments/assets/59416e3e-4498-4fec-bd96-435271f21ba1)

Pada halaman menu di halaman admin sudah terdapat pengaturan terkait menyusun menu yang ada, namun belum terdapat menu khusus untuk mengatur statisitk yang akan tampil seperti yang ada di OpenSID. 

![Image](https://github.com/user-attachments/assets/6f9dc136-0bde-4b9a-8f30-32ad1766eb91)

dari bentuk pengaturan yang ada di statistik penduduk maka menu ini perlu ditambahkan agar dapat disusun pada dasbor data presisi.

**Comment by agungsugiarto** [comment]
mas @vickyrolanda kurang lengkap informasinya, setelah ditambahkan menu lalu me-link kemana statistik tersebut?
