### ISSUE TITLE
Sediakan API Statistik berita di OpenKab

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#39]
1. Untuk statistik dimunculkan berdasarkan jumlah artikel dimana ada filter 
   - Perkelurahan
   - Perbulan 
   - Pertahun
   - Perkategori

2. Statistik yang muncul adalah jumlah artikel perkelurahan

**Comment by FirlianiF** [comment]
Tampilkan di dashboard utama

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenKab/pull/144
