### ISSUE TITLE
Butuh Siapkan API Data Pangan 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#412]
issue ini menjelaskan untuk kebutuhan data yang akan diterapkan pada halaman dasboar dengan issue terpisah data -data yang dibutuhkan di ambil dari database gabungan seperti berikut ini : 

Data berikut ini diambil dari sumber prodeskel dimana data pangan sudah lebih details : 

Kepemilikan Lahan  
- NIK
- Jenis Lahan
- Luas Lahan

Produksi Tanaman Pangan
- Jenis Komoditas
- Satuan
- Nilai
- Pemasaran Hasil 

Produksi Buah-buahan
- Jenis Komoditas
- Jumlah Pohon
- Produksi
- Satuan
- Nilai
- Pemasaran Hasil

Produksi Tanaman Obat
- Jenis Komoditas
- Produksi
- Satuan
- Nilai
- Pemasaran Hasil

Produksi Perkebunan
- Jenis Komoditas
- Produksi
- Satuan
- Nilai
- Pemasaran Hasil

Produksi Jenis Ternak
- Jenis Komoditas
- Produksi
- Satuan
- Nilai
- Pemasaran Hasil

Produksi Perikanan
- Jenis Komoditas
- Produksi
- Satuan
- Nilai
- Pemasaran Hasil

Pola Makan
- Belum tentu sehari makan 1 kali	
- Kebiasaan makan dalam sehari 1 kali
- Kebiasaan makan sehari 2 kali	
- Kebiasaan makan sehari 3 kali
- Kebiasaan makan sehari lebih dari 3 kali

dari kebutuhan data diatas semua sudah tersedia pada DDK modul prodeskel, dan  perlu dimuat dalam 1 API dengan multi dimensi.

**Comment by agungsugiarto** [comment]
@vickyrolanda Perlu contoh multidimensi data yg ditampilkan seperti apa yg dimaksud.
