### ISSUE TITLE
Butuh Siapkan data API untuk Papan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#413]
issue ini menjelaskan untuk kebutuhan data yang akan diterapkan pada halaman dasboar dengan issue terpisah data -data yang dibutuhkan di ambil dari database gabungan seperti berikut ini :

Data berikut ini diambil dari sumber prodeskel dimana data Papan sudah lebih details :

Data Papan diambil dari Data DTKS seperti berikut ini  : 
- Nik Kepala RTM
- Status kepemilikan bangunan tempat tinggal yang ditempati
- Luas Lantai (m2) 
- Jenis lantai terluas
- Jenis dinding terluas
- Jenis Atap terluas
- Sumber air minum
-  Sumber penerangan utama
- Bahan bakar/energi utama untuk memasak
- Kepemilikan dan penggunaan fasilitas tempat buang air besar
- Tempat pembuangan akhir tinja

data diatas dibuat kedalam sebuah API untuk kebtuuhan mendasar membentuk dasbor kebutuhan data papa.

**Comment by agungsugiarto** [comment]
mas @vickyrolanda perlu contoh data yg ditampilkan seperti apa
