### ISSUE TITLE
Butuh Siapkan API kebutuhan data presisi terkait kesehatan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#414]
issue ini menjelaskan untuk kebutuhan data yang akan diterapkan pada halaman dasbor dengan issue terpisah data -data yang dibutuhkan di ambil dari database gabungan seperti berikut ini maka data yang dibutuhkan adalah data kesehatan, data kesehatan ini diambil dari stuktur data di OpenSID yang telah tersedia pada menu penduduk berikut susunan data yang diperlukan : 

- NIK (data kependudukan)
- Golongan Darah  (data kependudukan)
- Cacat  (data kependudukan)
- Sakit Menahun  (data kependudukan)
- Akseptor KB  (data kependudukan)
- Status Kehamilan  (data kependudukan)
- Asuransi Kesehatan  (data kependudukan)
- Status Gizi Balita ( ambil dari data stunting)

data diatas perlu disusuk ke dalam sebuah API yang akan di manfaatkan untuk dasbor .

**Comment by FirlianiF** [comment]
http://127.0.0.1:8000/api/v1/data-kesehatan


`{
  "data": [
    {
      "type": "penduduk",
      "id": "11530",
      "attributes": {
        "nik": "5102101212820008",
        "nama": "I WAYAN BIRTAYASA",
        "golongan_darah_id": 13,
        "cacat_id": 7,
        "sakit_menahun_id": 14,
        "cara_kb_id": null,
        "hamil": null,
        "id_asuransi": 3,
        "no_asuransi": "0001238681643",
        "namaTempatDilahirkan": null,
        "namaJenisKelahiran": null,
        "namaPenolongKelahiran": null,
        "wajibKTP": "BELUM",
        "elKTP": null,
        "statusPerkawinan": "KAWIN BELUM TERCATAT",
        "statusHamil": "TIDAK HAMIL",
        "namaAsuransi": "BPJS Non Penerima Bantuan Iuran",
        "umur": null,
        "tanggalLahirId": null,
        "urlFoto": null,
        "namaGolonganDarah": "TIDAK TAHU",
        "namaCacat": "TIDAK CACAT",
        "namaSakitMenahun": "TIDAK ADA/TIDAK SAKIT",
        "namaKb": "TIDAK TAHU",
        "namaStuntingStatus": "TIDAK TAHU",
        "asuransi": {
          "id": 3,
          "nama": "BPJS Non Penerima Bantuan Iuran"
        },
        "golongan_darah": {
          "id": 13,
          "nama": "TIDAK TAHU"
        },
        "cacat": {
          "id": 7,
          "nama": "TIDAK CACAT"
        },
        "sakit_menahun": {
          "id": 14,
          "nama": "TIDAK ADA/TIDAK SAKIT"
        },
        "kb": [],
        "kia": null
      }
    },
    {
      "type": "penduduk",
      "id": "11531",
      "attributes": {
        "nik": "5102106904920001",
        "nama": "NI WAYAN TRISNA YANTI",
        "golongan_darah_id": 13,
        "cacat_id": null,
        "sakit_menahun_id": null,
        "cara_kb_id": null,
        "hamil": null,
        "id_asuransi": 3,
        "no_asuransi": "0001238681654",
        "namaTempatDilahirkan": null,
        "namaJenisKelahiran": null,
        "namaPenolongKelahiran": null,
        "wajibKTP": "BELUM",
        "elKTP": null,
        "statusPerkawinan": "KAWIN BELUM TERCATAT",
        "statusHamil": "TIDAK HAMIL",
        "namaAsuransi": "BPJS Non Penerima Bantuan Iuran",
        "umur": null,
        "tanggalLahirId": null,
        "urlFoto": null,
        "namaGolonganDarah": "TIDAK TAHU",
        "namaCacat": "TIDAK TAHU",
        "namaSakitMenahun": "TIDAK TAHU",
        "namaKb": "TIDAK TAHU",
        "namaStuntingStatus": "TIDAK TAHU",
        "asuransi": {
          "id": 3,
          "nama": "BPJS Non Penerima Bantuan Iuran"
        },
        "golongan_darah": {
          "id": 13,
          "nama": "TIDAK TAHU"
        },
        "cacat": [],
        "sakit_menahun": [],
        "kb": [],
        "kia": null
      }
    },
    {
      "type": "penduduk",
      "id": "11532",
      "attributes": {
        "nik": "5102104105090002",
        "nama": "NI PUTU RISMA YANI",
        "golongan_darah_id": 13,
        "cacat_id": null,
        "sakit_menahun_id": null,
        "cara_kb_id": null,
        "hamil": null,
        "id_asuransi": 3,
        "no_asuransi": "0001238681665",
        "namaTempatDilahirkan": null,
        "namaJenisKelahiran": null,
        "namaPenolongKelahiran": null,
        "wajibKTP": "BELUM",
        "elKTP": null,
        "statusPerkawinan": "KAWIN BELUM TERCATAT",
        "statusHamil": "TIDAK HAMIL",
        "namaAsuransi": "BPJS Non Penerima Bantuan Iuran",
        "umur": null,
        "tanggalLahirId": null,
        "urlFoto": null,
        "namaGolonganDarah": "TIDAK TAHU",
        "namaCacat": "TIDAK TAHU",
        "namaSakitMenahun": "TIDAK TAHU",
        "namaKb": "TIDAK TAHU",
        "namaStuntingStatus": "TIDAK TAHU",
        "asuransi": {
          "id": 3,
          "nama": "BPJS Non Penerima Bantuan Iuran"
        },
        "golongan_darah": {
          "id": 13,
          "nama": "TIDAK TAHU"
        },
        "cacat": [],
        "sakit_menahun": [],
        "kb": [],
        "kia": null
      }
    },
    {
      "type": "penduduk",
      "id": "11533",
      "attributes": {
        "nik": "5102101201170001",
        "nama": "I KADEK ADI WIRAWAN",
        "golongan_darah_id": 13,
        "cacat_id": null,
        "sakit_menahun_id": null,
        "cara_kb_id": null,
        "hamil": 2,
        "id_asuransi": 3,
        "no_asuransi": "0002215676193",
        "namaTempatDilahirkan": null,
        "namaJenisKelahiran": null,
        "namaPenolongKelahiran": null,
        "wajibKTP": "BELUM",
        "elKTP": null,
        "statusPerkawinan": "KAWIN BELUM TERCATAT",
        "statusHamil": "HAMIL",
        "namaAsuransi": "BPJS Non Penerima Bantuan Iuran",
        "umur": null,
        "tanggalLahirId": null,
        "urlFoto": null,
        "namaGolonganDarah": "TIDAK TAHU",
        "namaCacat": "TIDAK TAHU",
        "namaSakitMenahun": "TIDAK TAHU",
        "namaKb": "TIDAK TAHU",
        "namaStuntingStatus": "TIDAK TAHU",
        "asuransi": {
          "id": 3,
          "nama": "BPJS Non Penerima Bantuan Iuran"
        },
        "golongan_darah": {
          "id": 13,
          "nama": "TIDAK TAHU"
        },
        "cacat": [],
        "sakit_menahun": [],
        "kb": [],
        "kia": null
      }
    },
    {
      "type": "penduduk",
      "id": "11534",
      "attributes": {
        "nik": "8103010105860007",
        "nama": "I PUTU INDRA WINATA",
        "golongan_darah_id": 13,
        "cacat_id": null,
        "sakit_menahun_id": null,
        "cara_kb_id": null,
        "hamil": 2,
        "id_asuransi": 3,
        "no_asuransi": "0001483024847",
        "namaTempatDilahirkan": null,
        "namaJenisKelahiran": null,
        "namaPenolongKelahiran": null,
        "wajibKTP": "BELUM",
        "elKTP": null,
        "statusPerkawinan": "KAWIN BELUM TERCATAT",
        "statusHamil": "HAMIL",
        "namaAsuransi": "BPJS Non Penerima Bantuan Iuran",
        "umur": null,
        "tanggalLahirId": null,
        "urlFoto": null,
        "namaGolonganDarah": "TIDAK TAHU",
        "namaCacat": "TIDAK TAHU",
        "namaSakitMenahun": "TIDAK TAHU",
        "namaKb": "TIDAK TAHU",
        "namaStuntingStatus": "TIDAK TAHU",
        "asuransi": {
          "id": 3,
          "nama": "BPJS Non Penerima Bantuan Iuran"
        },
        "golongan_darah": {
          "id": 13,
          "nama": "TIDAK TAHU"
        },
        "cacat": [],
        "sakit_menahun": [],
        "kb": [],
        "kia": null
      }
    },
    {
      "type": "penduduk",
      "id": "11535",
      "attributes": {
        "nik": "5104024902880002",
        "nama": "NI KOMANG WITARI",
        "golongan_darah_id": 13,
        "cacat_id": null,
        "sakit_menahun_id": null,
        "cara_kb_id": null,
        "hamil": null,
        "id_asuransi": 3,
        "no_asuransi": "0001483029764",
        "namaTempatDilahirkan": null,
        "namaJenisKelahiran": null,
        "namaPenolongKelahiran": null,
        "wajibKTP": "BELUM",
        "elKTP": null,
        "statusPerkawinan": "KAWIN BELUM TERCATAT",
        "statusHamil": "TIDAK HAMIL",
        "namaAsuransi": "BPJS Non Penerima Bantuan Iuran",
        "umur": null,
        "tanggalLahirId": null,
        "urlFoto": null,
        "namaGolonganDarah": "TIDAK TAHU",
        "namaCacat": "TIDAK TAHU",
        "namaSakitMenahun": "TIDAK TAHU",
        "namaKb": "TIDAK TAHU",
        "namaStuntingStatus": "TIDAK TAHU",
        "asuransi": {
          "id": 3,
          "nama": "BPJS Non Penerima Bantuan Iuran"
        },
        "golongan_darah": {
          "id": 13,
          "nama": "TIDAK TAHU"
        },
        "cacat": [],
        "sakit_menahun": [],
        "kb": [],
        "kia": null
      }
    },
    {
      "type": "penduduk",
      "id": "11536",
      "attributes": {
        "nik": "8103012206130002",
        "nama": "I PUTU NARENDRA SATRIYA WIBAWA",
        "golongan_darah_id": 13,
        "cacat_id": null,
        "sakit_menahun_id": null,
        "cara_kb_id": null,
        "hamil": null,
        "id_asuransi": 3,
        "no_asuransi": "0001483031215",
        "namaTempatDilahirkan": null,
        "namaJenisKelahiran": null,
        "namaPenolongKelahiran": null,
        "wajibKTP": "BELUM",
        "elKTP": null,
        "statusPerkawinan": "KAWIN BELUM TERCATAT",
        "statusHamil": "TIDAK HAMIL",
        "namaAsuransi": "BPJS Non Penerima Bantuan Iuran",
        "umur": null,
        "tanggalLahirId": null,
        "urlFoto": null,
        "namaGolonganDarah": "TIDAK TAHU",
        "namaCacat": "TIDAK TAHU",
        "namaSakitMenahun": "TIDAK TAHU",
        "namaKb": "TIDAK TAHU",
        "namaStuntingStatus": "TIDAK TAHU",
        "asuransi": {
          "id": 3,
          "nama": "BPJS Non Penerima Bantuan Iuran"
        },
        "golongan_darah": {
          "id": 13,
          "nama": "TIDAK TAHU"
        },
        "cacat": [],
        "sakit_menahun": [],
        "kb": [],
        "kia": null
      }
    },
    {
      "type": "penduduk",
      "id": "11537",
      "attributes": {
        "nik": "5102103108870001",
        "nama": "I GEDE ADI SUANDIKA",
        "golongan_darah_id": 13,
        "cacat_id": null,
        "sakit_menahun_id": null,
        "cara_kb_id": null,
        "hamil": null,
        "id_asuransi": 3,
        "no_asuransi": "0001288152314",
        "namaTempatDilahirkan": null,
        "namaJenisKelahiran": null,
        "namaPenolongKelahiran": null,
        "wajibKTP": "BELUM",
        "elKTP": null,
        "statusPerkawinan": "KAWIN BELUM TERCATAT",
        "statusHamil": "TIDAK HAMIL",
        "namaAsuransi": "BPJS Non Penerima Bantuan Iuran",
        "umur": null,
        "tanggalLahirId": null,
        "urlFoto": null,
        "namaGolonganDarah": "TIDAK TAHU",
        "namaCacat": "TIDAK TAHU",
        "namaSakitMenahun": "TIDAK TAHU",
        "namaKb": "TIDAK TAHU",
        "namaStuntingStatus": "TIDAK TAHU",
        "asuransi": {
          "id": 3,
          "nama": "BPJS Non Penerima Bantuan Iuran"
        },
        "golongan_darah": {
          "id": 13,
          "nama": "TIDAK TAHU"
        },
        "cacat": [],
        "sakit_menahun": [],
        "kb": [],
        "kia": null
      }
    },
    {
      "type": "penduduk",
      "id": "11538",
      "attributes": {
        "nik": "5102106201870001",
        "nama": "NI KETUT SINTA DEWI",
        "golongan_darah_id": 13,
        "cacat_id": null,
        "sakit_menahun_id": null,
        "cara_kb_id": null,
        "hamil": null,
        "id_asuransi": 3,
        "no_asuransi": "0001288152202",
        "namaTempatDilahirkan": null,
        "namaJenisKelahiran": null,
        "namaPenolongKelahiran": null,
        "wajibKTP": "BELUM",
        "elKTP": null,
        "statusPerkawinan": "KAWIN BELUM TERCATAT",
        "statusHamil": "TIDAK HAMIL",
        "namaAsuransi": "BPJS Non Penerima Bantuan Iuran",
        "umur": null,
        "tanggalLahirId": null,
        "urlFoto": null,
        "namaGolonganDarah": "TIDAK TAHU",
        "namaCacat": "TIDAK TAHU",
        "namaSakitMenahun": "TIDAK TAHU",
        "namaKb": "TIDAK TAHU",
        "namaStuntingStatus": "TIDAK TAHU",
        "asuransi": {
          "id": 3,
          "nama": "BPJS Non Penerima Bantuan Iuran"
        },
        "golongan_darah": {
          "id": 13,
          "nama": "TIDAK TAHU"
        },
        "cacat": [],
        "sakit_menahun": [],
        "kb": [],
        "kia": null
      }
    },
    {
      "type": "penduduk",
      "id": "11539",
      "attributes": {
        "nik": "5102105204110001",
        "nama": "NI PUTU ANGEL AULIA SARI",
        "golongan_darah_id": 13,
        "cacat_id": null,
        "sakit_menahun_id": null,
        "cara_kb_id": null,
        "hamil": null,
        "id_asuransi": 3,
        "no_asuransi": "0001288152448",
        "namaTempatDilahirkan": null,
        "namaJenisKelahiran": null,
        "namaPenolongKelahiran": null,
        "wajibKTP": "BELUM",
        "elKTP": null,
        "statusPerkawinan": "KAWIN BELUM TERCATAT",
        "statusHamil": "TIDAK HAMIL",
        "namaAsuransi": "BPJS Non Penerima Bantuan Iuran",
        "umur": null,
        "tanggalLahirId": null,
        "urlFoto": null,
        "namaGolonganDarah": "TIDAK TAHU",
        "namaCacat": "TIDAK TAHU",
        "namaSakitMenahun": "TIDAK TAHU",
        "namaKb": "TIDAK TAHU",
        "namaStuntingStatus": "TIDAK TAHU",
        "asuransi": {
          "id": 3,
          "nama": "BPJS Non Penerima Bantuan Iuran"
        },
        "golongan_darah": {
          "id": 13,
          "nama": "TIDAK TAHU"
        },
        "cacat": [],
        "sakit_menahun": [],
        "kb": [],
        "kia": null
      }
    }
  ],
  "meta": {
    "pagination": {
      "total": 166762,
      "count": 10,
      "per_page": 10,
      "current_page": 1,
      "total_pages": 16677
    }
  },
  "links": {
    "self": "http://127.0.0.1:8000/api/v1/data-kesehatan?page[number]=1",
    "first": "http://127.0.0.1:8000/api/v1/data-kesehatan?page[number]=1",
    "next": "http://127.0.0.1:8000/api/v1/data-kesehatan?page[number]=2",
    "last": "http://127.0.0.1:8000/api/v1/data-kesehatan?page[number]=16677"
  }
}`
