### ISSUE TITLE
Tampilkan kategori berita berdasarkan API yang tersedia

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#42]
1. Kebutuhan kategori yang dapat di tambah melalui OpenKab adalah kategori yang sudah di tentukan oleh OpenKab untuk dapat di tampilkan ke masing -masing kategori kelurahan yang menggunakan OpenSID database gabungan.
2. Lalu Kategori yang ditambah melalui OpenKab tidak dapat di update ataupun di hapus oleh pengguna OpenSID database gabungan
3. Maka perlu ditambahkan logika pada rancangan awal ini dimana kategori yang akan ditambahkan oleh OpenKab akan memiliki id_openkab
4. lalu OpenSID database gabungan akan membaca jika kategori dengan id_openkab !== NULL  maka kategori tidak dapat di update ataupun di hapus namun dapat di gunakan dan tampil untuk semua OpenSID yang menggunakan database gabungan.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenKab/pull/122
