### ISSUE TITLE
Atur Pengaturan Untuk Perubahan Warna Tema & General kan setting aplikasi

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#44]
Pengaturan warna tema yang ada di OpenKab adalah pengaturan warna dengan model color picker dimana akan menyimpan kode warna seperti  #eab308 ,pengaturan akan tersimpan didatabse OpenKab dan dikirim langsung ke database gabungan ke Tabel setting_aplikasi dan parameter #key = warna_tema

dimana nantinya melalui parameter tersebut tema akan mengambil warna untuk disesuaikan ditema OpenSID database gabungan.

maka melalui batasan pengerjaan di OpenKab hanya mengubah warna tema sesuai pengaturan yang ada di database OpenKab lalu di kirim ke database gabungan.

issue OpenSID database gabungan https://github.com/OpenSID/OpenSID/issues/6560

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenKab/pull/159
