### ISSUE TITLE
API Identitas OpenKab

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenKab#6]
Identitas OpenKab bisa ditentukan untuk mengatur nama dari OpenKab, saat ini namanya adalah Simatik 
- Nama Aplikasi
- Deskripsi 
- Logo 
- fav-icon
- Pilih Kabupaten Kota

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenKab/pull/142
